project:
  type: website
  output-dir: docs

website:
  title: "15ª Regional de Saúde — Vigilância Epidemiológica"
  navbar:
    left:
      - href: index.qmd
        text: Início
      - text: "Vigilância Universal (SRAG)"
        href: srag.qmd
      - text: "Vigilância Sentinela (SG)"
        href: sindrome_gripal.qmd
      - href: sobre.qmd
        text: Sobre

format:
  html:
    theme: cosmo
    lang: pt
